spring:
  application:
    name: netflix
  datasource:
    url: jdbc:postgresql://localhost:5432/moviesdb
    password: password
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

