name: github-actions-workflow.yml
run-name: ${{ github.actor }} launch GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - develop
  pull_request:
jobs:
  init:
    name: Format check
    runs-on: ubuntu-latest

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
          cache: maven

      - name: Run the Maven validate phase
        run: ./mvnw clean validate

      - name: Check code formatting
        run: ./mvnw spotless:check

  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: init

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
          cache: maven

      - name: Run the Maven test phase
        run: ./mvnw clean test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
          cache: maven

      - name: Build Application
        run: ./mvnw -B clean package -DskipTests
